name: Apple Gift Card Monitor

on:
  schedule:
    # 0-6点（日本时间）：每30分钟一次
    - cron: '0,30 15-20 * * *'  # UTC时间15-20点对应JST 0-6点
    # 其他时间：每9分钟一次  
    - cron: '*/9 0-14,21-23 * * *'  # UTC时间0-14,21-23点对应JST 9-23,6-9点
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install chromium
        
    - name: Run monitor
      env:
        LINE_ACCESS_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
        LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
      run: |
        python monitor.py
